version: '3' 
services:
  
  impala-server:
    build:
      context: ./impala
      dockerfile: Dockerfile      
    image: ded/cdh6-impala-kudu
    hostname: impala-server
    container_name: impala-server
    ports:
      - "21050:21050"
      - "9083:9083"
      - "10000:10000"

  hue:
    image: fjardim/hue
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    volumes:
      - ./hue/hue-overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - database_hue
      - impala-server

  database_hue:
    image: fjardim/mysql
    container_name: database_hue
    hostname: database_hue
    ports:
        - "33061:3306"
    command: mysqld --innodb-flush-method=O_DSYNC --innodb-use-native-aio=OFF --init-file /data/application/init.sql
    volumes:
        - ./hue/mysql/data:/var/lib/mysql
        - ./hue/mysql/init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: hue
        MYSQL_USER: root
        MYSQL_PASSWORD: secret