version: '3' 
services:
  
  hive-server:
    image: fjardim/hive
    container_name: hive-server
    hostname: hive_server
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://impala-server/metastore"
      SERVICE_PRECONDITION: "impala-server:9083"
    ports:
      - "10000:10000"
    depends_on:
      - impala-server

  impala-server:   
    image: seqpipe/seqpipe-docker-impala
    hostname: impala-server
    container_name: impala-server
    ports:
      - "9083:9083"
      - "5432:5432"
      - "8020:8020"

  hue:
    image: fjardim/hue
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    volumes:
      - ./hue/hue-overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - database_hue
      - impala-server
      - hive-server

  database_hue:
    image: fjardim/mysql
    container_name: database_hue
    hostname: database_hue
    ports:
        - "33061:3306"
    command: mysqld --innodb-flush-method=O_DSYNC --innodb-use-native-aio=OFF --init-file /data/application/init.sql
    volumes:
        - ./hue/mysql/data:/var/lib/mysql
        - ./hue/mysql/init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: hue
        MYSQL_USER: root
        MYSQL_PASSWORD: secret